	<!---MENU DE CONTENIDO LATERAL-->
	<div class="lateral">
	<aside>
	<div class="buscar">
		    <form id="buscar" method="get" action="http://localhost/proy/">
            <fieldset>
			<input type="text" name="caja_buscador" class="caja_buscador" maxlength="40" size="0" placeholder="Search" />
            <input type="submit" name="boton_buscador" value="BUSCAR" />
          	</fieldset>
		  </form>
     </div>
	 <h2><span>Enlaces de inter&eacute;s</span></h2>
      <div class="links">
	  	<h4>
			<a href="http://www.umsa.bo/">Universidad Mayor de San &Aacute;ndres</a><br /><br />
   		  	<a href="http://www.umsa.bo/"><img src="images/umsa.gif" width="269" height="119" /></a><br /><br />
			<a href="http://miing.umsa.edu.bo/">Facultad de Ingenier&iacute;a UMSA</a><br /><br />
   		  	<a href="http://miing.umsa.edu.bo/"><img src="images/inge.gif" width="270" height="119" /></a><br /><br />
		</h4>
	 </div>
	</aside>
	</div>