<!---CONTENIDO-->
	<div class="contenido">
	<h1 id="titulo">Bienvenidos a &eacute;ste Blog</h1>
	<section>
	<article>En &eacute;sta p&aacute;gina encontrar&aacute;s informaci&oacute;n acerca de las actividades, curiosidades e informaci&oacute;n tecnol&oacute;gica donde participo y espero que les guste los aportes que se publica en &eacute;sta pagina.</article>
	<ul><span id="links">
	<li>En la secci&oacute;n &quot;<a href="work.php">Trabajos</a>&quot; podr&aacute;s encontrar detalles sobre mis trabajos y proyectos desarrollados, que han ocupado mi faceta acad&eacute;mica y cultural. </li>
	<li>En mi &quot;<a href="blog.php">Blog</a>&quot; encontrar&aacute;s art&iacute;culos y comentarios sobre tecnolog&iacute;a, Internet, informativa, y nuevos modelos de Propiedad Intelectual.</li>
	<li>A trav&eacute;s de las secci&oacute;n &quot;<a href="address.php">Contactos</a>&quot; puedes ponerte en contacto conmigo.</li></span>
	</ul>
	</section>
	</div>